title: Elina Ho
author: elinaho
email: elina8052@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi guys! I made this website using GitHub. It's my first project, I hope you guys like it! :)

# social links
instagram_username: elina_8052
github_username:  elinaho
show_excerpts: true # set to false to remove excerpts on the homepage

theme: architect
